# Generated by Django 3.0.4 on 2021-10-18 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='role',
            field=models.IntegerField(default='', max_length=10),
        ),
    ]
